// Copies the committed evidence/demo JSON from ../artifacts into web/data/ (gitignored,
// regenerated every dev/build start). Server Components read from web/data/ directly via
// fs -- this script exists only so the Next.js app is self-contained at build time inside
// a Vercel "Root Directory: web" monorepo checkout, without duplicating the committed
// files a second time in git. Never imported by client code; nothing here reaches the
// browser bundle.
import { copyFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const webDir = dirname(dirname(fileURLToPath(import.meta.url)));
const artifactsDir = join(webDir, "..", "artifacts");
const dataDir = join(webDir, "data");

const FILES = [
  "summary.json",
  "sensitivity.json",
  "recovery_model_report.json",
  "hazard_model_report.json",
  "money_chart_data.json",
  "demo_batch.json",
  "home_demo.json",
  "compliance_rules.json",
];

// Optional: the ask-why narratives (artifacts/llm_cache/ask_why.json) are generated by
// `make ask-why`, which requires a GEMINI_API_KEY and can take a while over the full demo
// batch -- so unlike FILES above, a missing cache doesn't fail the build. The frontend
// treats an absent or partial cache as "not generated for this decision yet", per
// components/AskWhyBox.tsx.
const OPTIONAL_FILES = ["llm_cache/ask_why.json"];

mkdirSync(dataDir, { recursive: true });
mkdirSync(join(dataDir, "llm_cache"), { recursive: true });

for (const name of FILES) {
  const src = join(artifactsDir, name);
  const dest = join(dataDir, name);
  if (!existsSync(src)) {
    throw new Error(
      `${src} not found -- run \`make eval\` / \`make demo-fixture\` from the repo root first.`,
    );
  }
  copyFileSync(src, dest);
}

let optionalSynced = 0;
for (const name of OPTIONAL_FILES) {
  const src = join(artifactsDir, name);
  const dest = join(dataDir, name);
  if (existsSync(src)) {
    copyFileSync(src, dest);
    optionalSynced += 1;
  }
}

console.log(
  `synced ${FILES.length} artifact files (+ ${optionalSynced}/${OPTIONAL_FILES.length} optional) into web/data/`,
);
