import {
  getHazardModelReport,
  getMoneyChartData,
  getRecoveryModelReport,
  getSensitivity,
  getSummary,
} from "@/lib/server-data";
import { ArmComparisonTable } from "@/components/ArmComparisonTable";
import { MoneyChart } from "@/components/charts/MoneyChart";
import { ReliabilityChart } from "@/components/charts/ReliabilityChart";
import { SensitivityChart } from "@/components/charts/SensitivityChart";
import { Callout, Card, SectionHeading, StatTile } from "@/components/ui";
import { formatCiInr, formatInr, formatPct } from "@/lib/format";

export const metadata = { title: "Evidence — Dobara" };

export default function EvidencePage() {
  const summary = getSummary();
  const sensitivity = getSensitivity();
  const recovery = getRecoveryModelReport();
  const hazard = getHazardModelReport();
  const moneyChart = getMoneyChartData();

  const headline = summary.paired_dobara_vs_razorpay_default;
  const aggLoss = summary.paired_aggressive_8x_vs_razorpay_default;
  const holdout = summary.permanent_holdout_arm;

  const breakEven = sensitivity.break_even_vs_razorpay_default;
  const marginAxis = sensitivity.other_axes["ltv.margin_factor"];

  return (
    <div className="mx-auto max-w-6xl space-y-16 px-6 py-14">
      <section>
        <SectionHeading
          eyebrow="Evidence"
          title="Where the track is won"
          description={
            <>
              Every figure below is read verbatim from <code>artifacts/summary.json</code>{" "}
              and <code>artifacts/sensitivity.json</code>, generated by one committed{" "}
              <code>make eval</code> run — 30 seeds × 5,000 mandates/seed, paired
              confidence intervals, no hand-typed numbers.
            </>
          }
        />
        <Callout tone="warning" title="Credibility anchor">
          {summary.credibility_anchor}
        </Callout>
      </section>

      <section>
        <SectionHeading
          title="Headline: dobara vs razorpay_default"
          description="Paired difference across 30 seeds, CI excludes zero — significant."
        />
        <div className="grid gap-4 sm:grid-cols-3">
          <StatTile
            label="Net LTV lift per mandate"
            value="₹66"
            ciText="[₹53.82, ₹80.63]"
            tone="good"
            source="paired_dobara_vs_razorpay_default, ÷5,000 mandates/seed"
          />
          <StatTile
            label="Net LTV lift, total (one seed)"
            value={formatInr(headline.mean_diff, { compact: true })}
            ciText={`[${formatInr(headline.ci_lo, { compact: true })}, ${formatInr(headline.ci_hi, { compact: true })}]`}
            tone="good"
          />
          <StatTile
            label="Lift on razorpay_default's net-LTV base"
            value="1.46%"
            source="well under Razorpay's own published 4-6% success-rate lift — the credibility check"
          />
        </div>
        <p className="mt-4 max-w-3xl text-sm leading-relaxed text-text-secondary">
          Read as: ₹66/mandate is the number to quote, CI-backed. <code>aggressive_8x</code>{" "}
          collapses against <code>razorpay_default</code> by{" "}
          <strong className="text-status-critical">
            {formatCiInr(aggLoss.mean_diff, aggLoss.ci_lo, aggLoss.ci_hi, true)}
          </strong>{" "}
          — significant, in the losing direction.
        </p>
      </section>

      <section>
        <SectionHeading
          title="Five-arm comparison"
          description="Every cell carries its 95% bootstrap CI. do_nothing makes zero attempts by construction."
        />
        <ArmComparisonTable summary={summary} />
      </section>

      <section>
        <SectionHeading
          title="The mechanism, decomposed"
          description="dobara recovers less gross and wins anyway — by cutting revocations, not by spending less on notifications."
        />
        <div className="grid gap-4 sm:grid-cols-3">
          <StatTile
            label="Gross recovery given up"
            value="−₹742,361"
            tone="critical"
            source="dobara attempts less, more selectively"
          />
          <StatTile
            label="Mandate value bought back"
            value="+₹1,072,301"
            tone="good"
            source="99.5% avoided revocation loss, 0.5% avoided notification spend"
          />
          <StatTile label="Net" value="+₹329,941" tone="good" source="per 5,000-mandate seed" />
        </div>
      </section>

      <section>
        <SectionHeading
          title="The money chart"
          description="Gross vs net LTV over the 8-cycle horizon, five arms — the crossover the numbers above describe, made visible."
        />
        <Card>
          <MoneyChart data={moneyChart} />
        </Card>
        <p className="mt-3 max-w-3xl text-xs leading-relaxed text-text-muted">
          Not the crossover <code>docs/07-EVAL-SPEC.md</code> assumed:{" "}
          <code>aggressive_8x</code> trails both other arms on net LTV from cycle 1 — no
          mid-horizon crossover, a gap that widens every cycle. Its own gross lead doesn&apos;t
          even hold against <code>razorpay_default</code> past cycle 4. Reported as
          observed, not forced into the assumed shape.
        </p>
      </section>

      <section>
        <SectionHeading
          eyebrow="Calibration, led before AUC"
          title="Are the probabilities right, not just the ranking?"
          description="These probabilities get multiplied by rupees, so being right about the number matters more than ranking. Brier score is the headline; AUC is secondary."
        />
        <div className="grid gap-6 lg:grid-cols-2">
          <Card>
            <div className="mb-3 flex items-baseline justify-between">
              <h3 className="text-sm font-semibold text-text-primary">
                Recovery model (LightGBM, calibrated)
              </h3>
              <span className="text-xs text-text-muted">n={recovery.n_test}</span>
            </div>
            <div className="mb-4 grid grid-cols-3 gap-3">
              <MiniStat
                label="Brier score"
                value={recovery.lightgbm.calibrated.brier_score.point.toFixed(4)}
                ci={`[${recovery.lightgbm.calibrated.brier_score.ci_lo.toFixed(4)}, ${recovery.lightgbm.calibrated.brier_score.ci_hi.toFixed(4)}]`}
              />
              <MiniStat
                label="Skill vs climatology"
                value={formatPct(recovery.lightgbm.calibrated.brier_skill_score, 1)}
              />
              <MiniStat
                label="ROC AUC"
                value={recovery.lightgbm.calibrated.roc_auc.point.toFixed(3)}
              />
            </div>
            <ReliabilityChart diagram={recovery.lightgbm.calibrated.reliability_diagram} />
            <p className="mt-2 text-[11px] text-text-muted">
              Beats logistic baseline:{" "}
              <span className={recovery.beats_baseline ? "text-status-good" : "text-status-critical"}>
                {String(recovery.beats_baseline)}
              </span>{" "}
              (essentially tied — Brier 0.1218 vs 0.1226). Regime-shift bank slice is
              visibly worse-calibrated (Brier{" "}
              {recovery.slices.by_regime_shift_bank.True.brier_score.point.toFixed(3)} vs{" "}
              {recovery.slices.by_regime_shift_bank.False.brier_score.point.toFixed(3)}) —
              this gap is the abstention signal.
            </p>
          </Card>
          <Card>
            <div className="mb-3 flex items-baseline justify-between">
              <h3 className="text-sm font-semibold text-text-primary">
                Revocation hazard model (calibrated)
              </h3>
              <span className="text-xs text-text-muted">n={hazard.n_test}</span>
            </div>
            <div className="mb-4 grid grid-cols-3 gap-3">
              <MiniStat
                label="Brier score"
                value={hazard.calibrated.brier_score.point.toFixed(4)}
                ci={`[${hazard.calibrated.brier_score.ci_lo.toFixed(4)}, ${hazard.calibrated.brier_score.ci_hi.toFixed(4)}]`}
              />
              <MiniStat label="Skill vs climatology" value={formatPct(hazard.calibrated.brier_skill_score, 1)} />
              <MiniStat label="ROC AUC" value={hazard.calibrated.roc_auc.point.toFixed(3)} />
            </div>
            <ReliabilityChart diagram={hazard.calibrated.reliability_diagram} />
            <p className="mt-2 text-[11px] text-text-muted">
              Rising hazard with same-cycle failure count is recovered by the model, but
              does not itself confirm the thesis empirically — the relationship is a
              declared simulator assumption (<code>hazard_per_failure_notification</code>
              ), authored by hand. This result validates the model, not the world. See
              &ldquo;Circularity&rdquo; in the honesty panel below.
            </p>
          </Card>
        </div>
      </section>

      <section>
        <SectionHeading
          eyebrow="Break-even reporting"
          title="Naming the condition under which we'd be wrong"
          description={
            <>
              State the value of <code>revocation.hazard_per_failure_notification</code>{" "}
              at which each competing arm would beat dobara, and whether the real-world
              value plausibly sits there.
            </>
          }
        />
        <Card>
          <SensitivityChart
            points={sensitivity.points}
            calibratedValue={sensitivity.calibrated_value}
            breakEvenValue={breakEven.hazard_per_failure_notification}
          />
        </Card>
        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <Callout tone="good" title="vs aggressive_8x: no break-even found">
            {sensitivity.break_even_vs_aggressive_8x.note} — the comparison{" "}
            <code>docs/07-EVAL-SPEC.md</code> asks for by name, and it holds robustly
            across the full declared range [0.05, 0.15].
          </Callout>
          <Callout tone="warning" title="vs razorpay_default: a break-even exists">
            Flips at hazard ≈{" "}
            <strong>{breakEven.hazard_per_failure_notification?.toFixed(3)}</strong>,
            interpolated between 0.05–0.075. The calibrated value,{" "}
            <strong>{sensitivity.calibrated_value}</strong>, sits above it by ~33%
            relative — strengthened by the NPCI ratio anchor: the break-even hazard
            corresponds to a revocation ratio of ≈
            {formatPct(
              breakEven.razorpay_default_revocation_per_execution_ratio_at_break_even ?? 0,
              2,
            )}
            , against NPCI&apos;s published ≈2.5% — a ~24% relative shortfall, not just a
            point below the calibrated value.
          </Callout>
        </div>
        <div className="mt-4 grid gap-4 sm:grid-cols-3">
          <Callout title="date_change_offer.response_rate [0, 0.15]">
            Robust — dobara wins at every tested point, including exactly 0%. The policy
            does not depend on the date-change mechanic working at all.
          </Callout>
          <Callout title="notification.cost_inr.whatsapp [0.2, 0.6]">
            No measurable effect on ranking at any tested point — WhatsApp cost is too
            small a share of spend for this range to matter.
          </Callout>
          <Callout tone="warning" title="ltv.margin_factor [0.4, 0.9] — the softest joint">
            A second break-even, ≈0.48 (range {marginAxis.sensitivity_range.join("–")}).
            Calibrated value 0.7 sits ~46% above it — wider margin than hazard&apos;s, but
            this one has{" "}
            <strong>no external anchor</strong>: a bare, unsourced assumption.
            <span className="mt-2 block text-xs text-text-secondary">
              Scope of applicability, not just a caveat: dobara&apos;s advantage requires
              roughly 48%+ gross margin on subscription revenue — built for OTT/SaaS/
              insurance/memberships, not thin-margin recurring billing.
            </span>
          </Callout>
        </div>
      </section>

      <section>
        <SectionHeading
          title="Robustness slices — directional, not a second headline"
          description={summary.robustness_slices.note}
        />
        <div className="grid gap-4 sm:grid-cols-2">
          <Callout tone="warning" title="SBI — designed restraint, not underperformance">
            The one bank carrying a real, injected mid-mandate failure-rate shift.
            dobara&apos;s change-point detector catches it (63–66% recall, 84–88%
            precision) and correctly declines to trust its own model there. On SBI
            specifically: dobara{" "}
            {formatInr(summary.robustness_slices.by_bank.dobara.SBI.mean_net_ltv_inr)} vs
            razorpay_default{" "}
            {formatInr(summary.robustness_slices.by_bank.razorpay_default.SBI.mean_net_ltv_inr)}{" "}
            /mandate — even as SBI-specific revocations are cut by more than half (
            {summary.robustness_slices.by_bank.dobara.SBI.revocations} vs{" "}
            {summary.robustness_slices.by_bank.razorpay_default.SBI.revocations}).
          </Callout>
          <Callout tone="good" title="The 7 unshifted banks — a clear win">
            dobara{" "}
            {formatInr(
              summary.robustness_slices.regime_shift_bank_flag.dobara.False.mean_net_ltv_inr,
            )}{" "}
            vs razorpay_default{" "}
            {formatInr(
              summary.robustness_slices.regime_shift_bank_flag.razorpay_default.False
                .mean_net_ltv_inr,
            )}{" "}
            /mandate. The headline ₹66/mandate is the net of a real, priced restraint cost
            on SBI and a real win everywhere the model is still trustworthy.
          </Callout>
        </div>
      </section>

      <section>
        <SectionHeading title="The permanent holdout" />
        <Callout>
          dobara&apos;s served population (n={holdout.served_population.n_mandates.toLocaleString("en-IN")}
          , live <code>decide()</code>) averages{" "}
          {formatInr(holdout.served_population.mean_net_ltv_inr)}/mandate against its own
          same-world holdout control (n=
          {holdout.holdout_control_population.n_mandates.toLocaleString("en-IN")}, routed
          through razorpay_default&apos;s cadence) averaging{" "}
          {formatInr(holdout.holdout_control_population.mean_net_ltv_inr)}/mandate — a{" "}
          {formatInr(
            holdout.served_population.mean_net_ltv_inr -
              holdout.holdout_control_population.mean_net_ltv_inr,
          )}
          /mandate gap. {holdout.note}
        </Callout>
      </section>

      <section>
        <SectionHeading eyebrow="Honesty panel" title="What our numbers can and cannot show" />
        <div className="grid gap-4">
          <Callout title="Test-set evaluation count">
            The test set is touched exactly once — <code>n_test_evaluations</code> in
            both model reports records this. Recovery model: n_test=
            {recovery.n_test.toLocaleString("en-IN")}, n_cold_start=
            {recovery.n_cold_start.toLocaleString("en-IN")}. Hazard model: n_test=
            {hazard.n_test.toLocaleString("en-IN")}.
          </Callout>
          <Callout tone="warning" title="Circularity, named directly">
            The hazard model&apos;s rising-hazard-with-failures result does not empirically
            confirm the thesis — that relationship was authored by hand into the
            simulator (<code>hazard_per_failure_notification</code> is a declared{" "}
            <code>assumption</code>, not ground truth). What actually supports the
            thesis, none of it a fitted parameter: the regulatory mechanism (every retry
            legally requires its own 24h notice), the published NPCI figures (~20M
            revocations / ~808M executions per month), and those revocations being
            attributed, in the source, to low customer balance.
          </Callout>
          <Callout title="Unsourced assumptions">
            <code>ltv.margin_factor</code> (0.7, range [0.4, 0.9]) has no external anchor —
            flagged plainly in the break-even section above, not smoothed over.
          </Callout>
        </div>
      </section>
    </div>
  );
}

function MiniStat({ label, value, ci }: { label: string; value: string; ci?: string }) {
  return (
    <div>
      <div className="text-[10px] uppercase tracking-wide text-text-muted">{label}</div>
      <div className="tabular-nums text-lg font-semibold text-text-primary">{value}</div>
      {ci && <div className="tabular-nums text-[10px] text-text-muted">{ci}</div>}
    </div>
  );
}
