import {
  getHazardModelReport,
  getMoneyChartData,
  getRecoveryModelReport,
  getSensitivity,
  getSummary,
} from "@/lib/server-data";
import { ArmComparisonTable } from "@/components/ArmComparisonTable";
import { MoneyChart } from "@/components/charts/MoneyChart";
import { ReliabilityChart } from "@/components/charts/ReliabilityChart";
import { SensitivityChart } from "@/components/charts/SensitivityChart";
import { Callout, Card, SectionHeading, StatTile } from "@/components/ui";
import { formatCiInr, formatInr, formatNumber, formatPct } from "@/lib/format";
import type { SensitivityJson, SummaryJson } from "@/lib/types";

export const metadata = { title: "Evidence — Dobara" };

export default function EvidencePage() {
  const summary = getSummary();
  const sensitivity = getSensitivity();
  const recovery = getRecoveryModelReport();
  const hazard = getHazardModelReport();
  const moneyChart = getMoneyChartData();

  const headline = summary.paired_dobara_vs_razorpay_default;
  const aggLoss = summary.paired_aggressive_8x_vs_razorpay_default;
  const holdout = summary.permanent_holdout_arm;
  const dobaraArm = summary.arms.dobara;
  const razorpayArm = summary.arms.razorpay_default;
  // Both derivable straight from the arm totals, not hand-typed: dobara recovers less
  // gross and wins anyway because what it buys back with that trade exceeds it.
  const grossGivenUp =
    dobaraArm.gross_recovered_inr.point! - razorpayArm.gross_recovered_inr.point!;
  const mandateValueBoughtBack = headline.mean_diff - grossGivenUp;

  const breakEven = sensitivity.break_even_vs_razorpay_default;
  const marginAxis = sensitivity.other_axes["ltv.margin_factor"];

  return (
    <div className="mx-auto max-w-6xl space-y-16 px-6 py-14">
      <section>
        <SectionHeading
          eyebrow="Evidence"
          title="Where the track is won"
          description={
            <>
              Every figure below is read verbatim from <code>artifacts/summary.json</code>{" "}
              and <code>artifacts/sensitivity.json</code>, generated by one committed{" "}
              <code>make eval</code> run — 30 seeds × 5,000 mandates/seed, paired
              confidence intervals, no hand-typed numbers.
            </>
          }
        />
        <Callout tone="warning" title="Credibility anchor">
          {summary.credibility_anchor}
        </Callout>
      </section>

      <section>
        <SectionHeading
          title="Headline: dobara vs razorpay_default"
          description="Paired difference across 30 seeds, CI excludes zero — significant."
        />
        <div className="grid gap-4 sm:grid-cols-3">
          <StatTile
            label="Net LTV lift per mandate"
            value={formatInr(headline.mean_diff / summary.n_customers_per_seed, {
              compact: false,
            })}
            ciText={`[${formatInr(headline.ci_lo / summary.n_customers_per_seed)}, ${formatInr(headline.ci_hi / summary.n_customers_per_seed)}]`}
            tone="good"
            source={`paired_dobara_vs_razorpay_default, ÷${summary.n_customers_per_seed.toLocaleString("en-IN")} mandates/seed`}
          />
          <StatTile
            label="Net LTV lift, total (one seed)"
            value={formatInr(headline.mean_diff, { compact: true })}
            ciText={`[${formatInr(headline.ci_lo, { compact: true })}, ${formatInr(headline.ci_hi, { compact: true })}]`}
            tone="good"
          />
          <StatTile
            label="Lift on razorpay_default's net-LTV base"
            value={formatPct(headline.mean_diff / summary.arms.razorpay_default.net_ltv_total.point!, 2)}
            source="well under Razorpay's own published 4-6% success-rate lift — the credibility check"
          />
        </div>
        <p className="mt-4 max-w-3xl text-sm leading-relaxed text-text-secondary">
          Read as: {formatInr(headline.mean_diff / summary.n_customers_per_seed)}/mandate
          is the number to quote, CI-backed. <code>aggressive_8x</code> collapses against{" "}
          <code>razorpay_default</code> by{" "}
          <strong className="text-status-critical">
            {formatCiInr(aggLoss.mean_diff, aggLoss.ci_lo, aggLoss.ci_hi, true)}
          </strong>{" "}
          — significant, in the losing direction.
        </p>
        <p className="mt-3 max-w-3xl text-xs leading-relaxed text-text-muted">
          Rerun {formatTimestamp(summary.provenance.generated_at)} at commit{" "}
          <code>{summary.provenance.git_commit.slice(0, 12)}</code>, after{" "}
          <code>agent/decide.py</code>&apos;s tie-break fix (
          <a
            href="#tie-break-honesty"
            className="underline decoration-dotted hover:text-text-secondary"
          >
            see the honesty panel
          </a>
          ) — the previous run (26 Aug, pre-tie-break-fix) reported ₹65.99/mandate
          [₹53.82, ₹80.63]. Pre-registered before this rerun in{" "}
          <code>docs/DECISIONS.md</code> [2026-08-27]: the rule is kept regardless of
          which way the number moved. It moved by{" "}
          <strong>
            {signedInr(headline.mean_diff / summary.n_customers_per_seed - 65.99)}
          </strong>
          /mandate — a rounding-level change, not a regression.
        </p>
      </section>

      <section>
        <SectionHeading
          title="Five-arm comparison"
          description="Every cell carries its 95% bootstrap CI. do_nothing makes zero attempts by construction."
        />
        <ArmComparisonTable summary={summary} />
      </section>

      <section>
        <SectionHeading
          title="The mechanism, decomposed"
          description="dobara recovers less gross and wins anyway — cutting revocations far more than it cuts notification spend."
        />
        <div className="grid gap-4 sm:grid-cols-3">
          <StatTile
            label="Gross recovery given up"
            value={formatInr(grossGivenUp, { compact: true })}
            tone="critical"
            source="dobara attempts less, more selectively"
          />
          <StatTile
            label="Mandate value bought back"
            value={formatInr(mandateValueBoughtBack, { compact: true })}
            tone="good"
            source={`revocations ${formatNumber(dobaraArm.revocations_total.point!)} vs ${formatNumber(razorpayArm.revocations_total.point!)}; notifications ${formatNumber(dobaraArm.notifications_total.point!)} vs ${formatNumber(razorpayArm.notifications_total.point!)}`}
          />
          <StatTile
            label="Net"
            value={formatInr(headline.mean_diff, { compact: true })}
            tone="good"
            source={`per ${summary.n_customers_per_seed.toLocaleString("en-IN")}-mandate seed`}
          />
        </div>
        <p className="mt-3 max-w-3xl text-xs leading-relaxed text-text-muted">
          dobara cuts revocations{" "}
          {formatPct(
            1 - dobaraArm.revocations_total.point! / razorpayArm.revocations_total.point!,
            0,
          )}{" "}
          ({formatNumber(dobaraArm.revocations_total.point!)} vs{" "}
          {formatNumber(razorpayArm.revocations_total.point!)}) while sending{" "}
          {formatPct(
            1 -
              dobaraArm.notifications_total.point! / razorpayArm.notifications_total.point!,
            0,
          )}{" "}
          fewer notifications ({formatNumber(dobaraArm.notifications_total.point!)} vs{" "}
          {formatNumber(razorpayArm.notifications_total.point!)}) — the much larger
          relative cut is in revocations, the channel this thesis is built on, not
          notification cost savings.
        </p>
      </section>

      <section>
        <SectionHeading
          title="The money chart"
          description="Gross vs net LTV over the 8-cycle horizon, five arms — the crossover the numbers above describe, made visible."
        />
        <Card>
          <MoneyChart data={moneyChart} />
        </Card>
        <p className="mt-3 max-w-3xl text-xs leading-relaxed text-text-muted">
          Not the crossover <code>docs/07-EVAL-SPEC.md</code> assumed:{" "}
          <code>aggressive_8x</code> trails both other arms on net LTV from cycle 1 — no
          mid-horizon crossover, a gap that widens every cycle. Its own gross lead doesn&apos;t
          even hold against <code>razorpay_default</code> past cycle 4. Reported as
          observed, not forced into the assumed shape.
        </p>
      </section>

      <section>
        <SectionHeading
          eyebrow="Calibration, led before AUC"
          title="Are the probabilities right, not just the ranking?"
          description="These probabilities get multiplied by rupees, so being right about the number matters more than ranking. Brier score is the headline; AUC is secondary."
        />
        <div className="grid gap-6 lg:grid-cols-2">
          <Card>
            <div className="mb-3 flex items-baseline justify-between">
              <h3 className="text-sm font-semibold text-text-primary">
                Recovery model (LightGBM, calibrated)
              </h3>
              <span className="text-xs text-text-muted">n={recovery.n_test}</span>
            </div>
            <div className="mb-4 grid grid-cols-3 gap-3">
              <MiniStat
                label="Brier score"
                value={recovery.lightgbm.calibrated.brier_score.point.toFixed(4)}
                ci={`[${recovery.lightgbm.calibrated.brier_score.ci_lo.toFixed(4)}, ${recovery.lightgbm.calibrated.brier_score.ci_hi.toFixed(4)}]`}
              />
              <MiniStat
                label="Skill vs climatology"
                value={formatPct(recovery.lightgbm.calibrated.brier_skill_score, 1)}
              />
              <MiniStat
                label="ROC AUC"
                value={recovery.lightgbm.calibrated.roc_auc.point.toFixed(3)}
              />
            </div>
            <ReliabilityChart diagram={recovery.lightgbm.calibrated.reliability_diagram} />
            <p className="mt-2 text-[11px] text-status-warning">
              The visible steps are real, not a rendering artifact: this calibrator
              (isotonic regression, a step function by construction) emits only{" "}
              <strong>17 distinct probability values</strong> across [0, 1]. See
              &ldquo;Isotonic calibration is a step function&rdquo; in the honesty panel
              below for what that costs.
            </p>
            <p className="mt-2 text-[11px] text-text-muted">
              Beats logistic baseline:{" "}
              <span className={recovery.beats_baseline ? "text-status-good" : "text-status-critical"}>
                {String(recovery.beats_baseline)}
              </span>{" "}
              (essentially tied — Brier 0.1218 vs 0.1226). Regime-shift bank slice is
              visibly worse-calibrated (Brier{" "}
              {recovery.slices.by_regime_shift_bank.True.brier_score.point.toFixed(3)} vs{" "}
              {recovery.slices.by_regime_shift_bank.False.brier_score.point.toFixed(3)}) —
              this gap is the abstention signal.
            </p>
          </Card>
          <Card>
            <div className="mb-3 flex items-baseline justify-between">
              <h3 className="text-sm font-semibold text-text-primary">
                Revocation hazard model (calibrated)
              </h3>
              <span className="text-xs text-text-muted">n={hazard.n_test}</span>
            </div>
            <div className="mb-4 grid grid-cols-3 gap-3">
              <MiniStat
                label="Brier score"
                value={hazard.calibrated.brier_score.point.toFixed(4)}
                ci={`[${hazard.calibrated.brier_score.ci_lo.toFixed(4)}, ${hazard.calibrated.brier_score.ci_hi.toFixed(4)}]`}
              />
              <MiniStat label="Skill vs climatology" value={formatPct(hazard.calibrated.brier_skill_score, 1)} />
              <MiniStat label="ROC AUC" value={hazard.calibrated.roc_auc.point.toFixed(3)} />
            </div>
            <ReliabilityChart diagram={hazard.calibrated.reliability_diagram} />
            <p className="mt-2 text-[11px] text-status-warning">
              Same step-function calibrator, coarser here: <strong>8 distinct
              probability values</strong> across [0, 1] (n_validate is smaller for this
              model, so isotonic regression has fewer points to fit steps to).
            </p>
            <p className="mt-2 text-[11px] text-text-muted">
              Rising hazard with same-cycle failure count is recovered by the model, but
              does not itself confirm the thesis empirically — the relationship is a
              declared simulator assumption (<code>hazard_per_failure_notification</code>
              ), authored by hand. This result validates the model, not the world. See
              &ldquo;Circularity&rdquo; in the honesty panel below.
            </p>
          </Card>
        </div>
      </section>

      <section>
        <SectionHeading
          eyebrow="Break-even reporting"
          title="Naming the condition under which we'd be wrong"
          description={
            <>
              State the value of <code>revocation.hazard_per_failure_notification</code>{" "}
              at which each competing arm would beat dobara, and whether the real-world
              value plausibly sits there.
            </>
          }
        />
        <Card>
          <SensitivityChart
            points={sensitivity.points}
            calibratedValue={sensitivity.calibrated_value}
            breakEvenValue={breakEven.hazard_per_failure_notification}
          />
        </Card>
        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <Callout tone="good" title="vs aggressive_8x: no break-even found">
            {sensitivity.break_even_vs_aggressive_8x.note} — the comparison{" "}
            <code>docs/07-EVAL-SPEC.md</code> asks for by name, and it holds robustly
            across the full declared range [0.05, 0.15].
          </Callout>
          <Callout tone="warning" title="vs razorpay_default: a break-even exists">
            Flips at hazard ≈{" "}
            <strong>{breakEven.hazard_per_failure_notification?.toFixed(3)}</strong>,
            interpolated between 0.05–0.075. The calibrated value,{" "}
            <strong>{sensitivity.calibrated_value}</strong>, sits above it by ~33%
            relative — strengthened by the NPCI ratio anchor: the break-even hazard
            corresponds to a revocation ratio of ≈
            {formatPct(
              breakEven.razorpay_default_revocation_per_execution_ratio_at_break_even ?? 0,
              2,
            )}
            , against NPCI&apos;s published ≈2.5% — a ~24% relative shortfall, not just a
            point below the calibrated value.
          </Callout>
        </div>
        <div className="mt-4 grid gap-4 sm:grid-cols-3">
          <Callout title="date_change_offer.response_rate [0, 0.15]">
            Robust — dobara wins at every tested point, including exactly 0%. The policy
            does not depend on the date-change mechanic working at all.
          </Callout>
          <Callout title="notification.cost_inr.whatsapp [0.2, 0.6]">
            No measurable effect on ranking at any tested point — WhatsApp cost is too
            small a share of spend for this range to matter.
          </Callout>
          <Callout tone="warning" title="ltv.margin_factor [0.4, 0.9] — the softest joint">
            A second break-even, ≈0.48 (range {marginAxis.sensitivity_range.join("–")}).
            Calibrated value 0.7 sits ~46% above it — wider margin than hazard&apos;s, but
            this one has{" "}
            <strong>no external anchor</strong>: a bare, unsourced assumption.
            <span className="mt-2 block text-xs text-text-secondary">
              Scope of applicability, not just a caveat: dobara&apos;s advantage requires
              roughly 48%+ gross margin on subscription revenue — built for OTT/SaaS/
              insurance/memberships, not thin-margin recurring billing.
            </span>
          </Callout>
        </div>
      </section>

      <section>
        <SectionHeading
          title="Robustness slices — directional, not a second headline"
          description={summary.robustness_slices.note}
        />
        <div className="grid gap-4 sm:grid-cols-2">
          <Callout tone="warning" title="SBI — designed restraint, not underperformance">
            The one bank carrying a real, injected mid-mandate failure-rate shift.
            dobara&apos;s change-point detector catches it (63–66% recall, 84–88%
            precision) and correctly declines to trust its own model there. On SBI
            specifically: dobara{" "}
            {formatInr(summary.robustness_slices.by_bank.dobara.SBI.mean_net_ltv_inr)} vs
            razorpay_default{" "}
            {formatInr(summary.robustness_slices.by_bank.razorpay_default.SBI.mean_net_ltv_inr)}{" "}
            /mandate — even as SBI-specific revocations are cut by more than half (
            {summary.robustness_slices.by_bank.dobara.SBI.revocations} vs{" "}
            {summary.robustness_slices.by_bank.razorpay_default.SBI.revocations}).
          </Callout>
          <Callout tone="good" title="The 7 unshifted banks — a clear win">
            dobara{" "}
            {formatInr(
              summary.robustness_slices.regime_shift_bank_flag.dobara.False.mean_net_ltv_inr,
            )}{" "}
            vs razorpay_default{" "}
            {formatInr(
              summary.robustness_slices.regime_shift_bank_flag.razorpay_default.False
                .mean_net_ltv_inr,
            )}{" "}
            /mandate. The headline ₹66/mandate is the net of a real, priced restraint cost
            on SBI and a real win everywhere the model is still trustworthy.
          </Callout>
        </div>
      </section>

      <section>
        <SectionHeading title="The permanent holdout" />
        <Callout>
          dobara&apos;s served population (n={holdout.served_population.n_mandates.toLocaleString("en-IN")}
          , live <code>decide()</code>) averages{" "}
          {formatInr(holdout.served_population.mean_net_ltv_inr)}/mandate against its own
          same-world holdout control (n=
          {holdout.holdout_control_population.n_mandates.toLocaleString("en-IN")}, routed
          through razorpay_default&apos;s cadence) averaging{" "}
          {formatInr(holdout.holdout_control_population.mean_net_ltv_inr)}/mandate — a{" "}
          {formatInr(
            holdout.served_population.mean_net_ltv_inr -
              holdout.holdout_control_population.mean_net_ltv_inr,
          )}
          /mandate gap. {holdout.note}
        </Callout>
      </section>

      <section>
        <SectionHeading eyebrow="Honesty panel" title="What our numbers can and cannot show" />
        <div className="grid gap-4">
          <Callout title="Test-set evaluation count">
            The test set is touched exactly once — <code>n_test_evaluations</code> in
            both model reports records this. Recovery model: n_test=
            {recovery.n_test.toLocaleString("en-IN")}, n_cold_start=
            {recovery.n_cold_start.toLocaleString("en-IN")}. Hazard model: n_test=
            {hazard.n_test.toLocaleString("en-IN")}.
          </Callout>
          <Callout tone="warning" title="Circularity, named directly">
            The hazard model&apos;s rising-hazard-with-failures result does not empirically
            confirm the thesis — that relationship was authored by hand into the
            simulator (<code>hazard_per_failure_notification</code> is a declared{" "}
            <code>assumption</code>, not ground truth). What actually supports the
            thesis, none of it a fitted parameter: the regulatory mechanism (every retry
            legally requires its own 24h notice), the published NPCI figures (~20M
            revocations / ~808M executions per month), and those revocations being
            attributed, in the source, to low customer balance.
          </Callout>
          <Callout title="Unsourced assumptions">
            <code>ltv.margin_factor</code> (0.7, range [0.4, 0.9]) has no external anchor —
            flagged plainly in the break-even section above, not smoothed over.
          </Callout>
          <Callout
            id="tie-break-honesty"
            tone="warning"
            title="Isotonic calibration is a step function — and it costs real decision resolution"
          >
            Both models&apos; probability calibrators are <code>sklearn.isotonic.IsotonicRegression</code>,
            which by construction outputs a piecewise-constant step function, not a
            smooth curve — visible directly in the reliability diagrams above as flat
            segments, not a rendering artifact. Measured exactly, not approximated: the
            recovery model&apos;s LightGBM calibrator has <strong>17 distinct output
            values</strong> across [0, 1] (33 knots, fit on the validation split,
            n_validate={recovery.n_validate.toLocaleString("en-IN")}); its logistic
            baseline has <strong>15</strong>; the hazard
            model&apos;s calibrator has <strong>8</strong> (fewer knots — a smaller
            validation set). This is what it costs: many genuinely different raw
            predictions — the underlying LightGBM model does learn real
            day-of-month/day-of-week signal, confirmed by nonzero feature importance —
            collapse to an identical calibrated probability once the isotonic step
            swallows them. On the committed demo fixture this produced an exact{" "}
            <code>E[net]</code> tie at the argmax in 76% of decisions, some spanning
            candidate dates a month apart — not a bug in candidate scoring, a resolution
            ceiling in the calibrator. <code>agent/decide.py</code>&apos;s tie-break rule
            (closest to the customer&apos;s declared preferred day, else earliest date)
            exists specifically to give a principled answer at exactly the granularity
            the calibrator can no longer discriminate. Full diagnosis in{" "}
            <code>docs/DECISIONS.md</code> [2026-08-27].
          </Callout>
        </div>
      </section>

      <ProvenanceFooter summary={summary} sensitivity={sensitivity} />
    </div>
  );
}

function ProvenanceFooter({
  summary,
  sensitivity,
}: {
  summary: SummaryJson;
  sensitivity: SensitivityJson;
}) {
  const same = summary.provenance.git_commit === sensitivity.provenance.git_commit;
  return (
    <div className="border-t border-border pt-4 text-[11px] text-text-muted">
      <p>
        <code>summary.json</code> generated {formatTimestamp(summary.provenance.generated_at)}{" "}
        at commit <code>{summary.provenance.git_commit.slice(0, 12)}</code>.{" "}
        {!same && (
          <>
            <code>sensitivity.json</code> generated{" "}
            {formatTimestamp(sensitivity.provenance.generated_at)} at commit{" "}
            <code>{sensitivity.provenance.git_commit.slice(0, 12)}</code>.{" "}
          </>
        )}
        Checked by <code>make check</code>&apos;s <code>check_artifact_freshness</code>{" "}
        step against every later commit touching <code>agent/</code>, <code>models/</code>,{" "}
        <code>eval/</code>, or <code>sim/</code> — this page is never quoting numbers from
        a policy the code has since changed.
      </p>
    </div>
  );
}

function signedInr(value: number): string {
  const sign = value < 0 ? "−" : "+";
  return `${sign}₹${Math.abs(value).toFixed(2)}`;
}

function formatTimestamp(iso: string): string {
  return new Date(iso).toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "UTC",
  }) + " UTC";
}

function MiniStat({ label, value, ci }: { label: string; value: string; ci?: string }) {
  return (
    <div>
      <div className="text-[10px] uppercase tracking-wide text-text-muted">{label}</div>
      <div className="tabular-nums text-lg font-semibold text-text-primary">{value}</div>
      {ci && <div className="tabular-nums text-[10px] text-text-muted">{ci}</div>}
    </div>
  );
}
